name: lf toolchain install
author: Erling Rennemo Jellum
description: Install the LF toolchain
branding:
  icon: activity
  color: purple

runs:
  using: composite
  steps:
    - name: Parse toolchain version
      run: |
        TOOLCHAIN_VERSION="${GITHUB_REF#*@}"
        echo "version=$TOOLCHAIN_VERSION" >> $GITHUB_ENV
      shell: bash
    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Install LFC
      run: |
        set -e
        curl -Ls https://install.lf-lang.org | bash -s cli ${{ env.version }}
      shell: bash
    - name: Install lingo
      run: |
        cargo install lingua-franca
      shell: bash